### ISSUE TITLE
Error by scan image 

### ISSUE THREAD

**Issue by 53845714nF** [kvesta/vesta#52]
I use the following Command: `sudo ./vesta scan image ghcr.io/53845714nf/marketminder/backend`
The image is in the OCI Format, is this a problem? (The image is also Public for testing)

The Error is this:
```
2024/06/27 17:12:11 Searching for image
2024/06/27 17:12:32 Begin updating vulnerability database
2024/06/27 17:12:32 Vulnerability Database is already initialized
2024/06/27 17:12:32 Begin to analyze the layer
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
github.com/kvesta/vesta/pkg/layer.(*Manifest).GetLayers(0xc00010e300, {0x40b166?, 0x50f930?}, 0x1a8ba18?, {0xc000478140?, 0x15e2cc0?})
        /home/rar/Software_Projekte/vesta/pkg/layer/integrator.go:65 +0xa91
github.com/kvesta/vesta/internal.Inspect({0x1a8ba18, 0xc000271410}, {0xc000478140, 0x42}, 0xc0001658c8)
        /home/rar/Software_Projekte/vesta/internal/inspect.go:12 +0x5a
github.com/kvesta/vesta/internal.Extract({0x1a8ba18, 0xc000271410}, {0x0, 0x0}, {0xc0004bb100, 0x1, 0xc8?})
        /home/rar/Software_Projekte/vesta/internal/extract.go:86 +0x365
github.com/kvesta/vesta/internal.DoScan({0x1a8ba18, 0xc000271410}, {0x0, 0x0}, {0xc0004bb100, 0x1, 0x1})
        /home/rar/Software_Projekte/vesta/internal/utils.go:44 +0x25b
github.com/kvesta/vesta/cli.scan.func1(0xc0004b6800?, {0xc00004f050, 0x1, 0x182e3e8?})
        /home/rar/Software_Projekte/vesta/cli/scan.go:72 +0x23d
github.com/spf13/cobra.(*Command).execute(0xc0003882c8, {0xc00004f020, 0x1, 0x1})
        /home/rar/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x69b
github.com/spf13/cobra.(*Command).ExecuteC(0x25b90a0)
        /home/rar/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
        /home/rar/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/kvesta/vesta/cli.Execute()
        /home/rar/Software_Projekte/vesta/cli/command.go:69 +0x15e
main.main()
        /home/rar/Software_Projekte/vesta/cmd/vesta/main.go:11 +0x17
```

**Comment by christasa** [comment]
The infrastructure of docker image has been changed after docker 25+, we are currently adapting the image layer after this version. 

Or you can export the image via Docker before Docker version 25.0.0.

**Comment by 53845714nF** [comment]
Is that Docker only, as I have already written it is the OCI format.

**Comment by christasa** [comment]
Sorry for the late reply. It's not related to OCI format, it's related to Docker only.

**Comment by 53845714nF** [comment]
My Docker Version is `Docker version 27.0.3, build 7d4bcd8`
For Building the Image I use buildah-build Action V2 (redhat-actions/buildah-build@v2).

**Comment by christasa** [comment]
It's only related to Docker, since Docker has changed the storage structure of its images after Docker Version 25.0.0.

Although the image was not built using Docker, it was loaded into Docker. Vesta's `scan image` is scanned through the images stored in Docker, and its structure has now changed.

Vesta has not yet completed the adaptation to the new structure. You can either wait for finish the adaptation or temporarily use a Docker Version below 25.0.0 for image loading and image scanning.

**Comment by 53845714nF** [comment]
Do you know how I install this? I tried to install Docker-ce-cli and containerd.io in version 25 from here: https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/ 

But I get the error message that the engine is not running.

**Comment by christasa** [comment]
You might need to completely uninstall Docker first and then reinstall the Docker Version that is below 25.0.0. 

Or you can wait for a while, as adapting to the new image structure is in progress.

**Comment by 53845714nF** [comment]
Works very well. Thank you for your work.
